name: Linting

on:
  push:
    branches:
      - master
      - develop

  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install
      run: |
        python -m pip install -U pip
        python -m pip install -r test_requirements.txt